# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

pod 'MJRefresh', '~> 3.0.8'
pod 'Bugly', '~> 1.4.4'            #QQBugly
pod 'UMengAnalytics', '~> 3.6.6'    #标准SDK，含IDFA
pod 'UMengSocial', '~> 4.4'          #友盟分享
#pod 'AFNetworking', '~> 3.0.4'

target 'AllHelper' do

end

target 'AllHelperTests' do

end

target 'AllHelperUITests' do

end

